---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readers
  namespace: vote
subjects:
- kind: Group
  name: readers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: readers
  apiGroup: rbac.authorization.k8s.io

