---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: stage
  namespace: vote
spec:
  hard:
    requests.cpu: "0.5"
    requests.memory: "500Mi"
    limits.cpu: "2"
    limits.memory: "2Gi"
    count/deployments.apps: 8
