apiVersion: extensions/v1beta
kind: Ingress
metadata:
  name: vote
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: vote.ad.com
      http:
        paths:
          - path: /
            backend:
              serviceName: vote
              servicePort: 5000
    - host: results.ad.com
      http:
        paths:
          - path: /
            backend:
              serviceName: result
              servicePort: 5001
